version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: pitchpilot
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: pitchpilot_db
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: "5050"
      PGADMIN_DISABLE_TELEMETRY: "true"
    ports:
      - "5050:5050"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

  migrate:
    build: ../../
    command: alembic upgrade head
    env_file: ../../.env
    volumes:
      - ../../:/app
    depends_on:
      - db
    restart: "no"

  backend:
    build: ../../
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    env_file: ../../.env
    volumes:
      - ../../:/app
    ports:
      - "8000:8000"
    depends_on:
      migrate:
        condition: service_completed_successfully

  frontend:
    image: node:20-alpine
    working_dir: /app
    command: >
      sh -c "npm install &&
             npx next dev -H 0.0.0.0 -p 3000"
    volumes:
      - ../../../pitch-pilot-fe:/app
    ports:
      - "3000:3000"
    env_file: ../../../pitch-pilot-fe/.env
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  createbucket:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5 &&
      mc alias set local http://minio:9000 minioadmin minioadmin &&
      mc mb local/pitchpilot &&
      mc anonymous set download local/pitchpilot
      "

volumes:
  dbdata:
  pgadmin_data:
  minio_data: