"""empty message

Revision ID: 255e1c6ac1a9
Revises: 57b9b469c787
Create Date: 2025-06-19 22:53:06.041768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '255e1c6ac1a9'
down_revision: Union[str, Sequence[str], None] = '57b9b469c787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trainings', 'total_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Total score for the training session',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trainings', 'total_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Total score for the training session',
               existing_nullable=False)
    # ### end Alembic commands ###
