"""add eye tracking columns

Revision ID: 8346b5ac5174
Revises: 21b2ec136547
Create Date: 2025-06-21 16:39:53.548353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8346b5ac5174'
down_revision: Union[str, Sequence[str], None] = '21b2ec136547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainings', sa.Column('eye_tracking_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Heatmap/Score aus Eye Tracking'))
    op.add_column('trainings', sa.Column('eye_tracking_total_score', sa.Float(), nullable=True, comment='Finaler Eye Tracking Score'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainings', 'eye_tracking_total_score')
    op.drop_column('trainings', 'eye_tracking_scores')
    # ### end Alembic commands ###
