"""empty message

Revision ID: 9e29798b8fdf
Revises: e2c31ae2a80c
Create Date: 2025-06-19 22:36:57.851668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e29798b8fdf'
down_revision: Union[str, Sequence[str], None] = 'e2c31ae2a80c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainings', sa.Column('duration_seconds', sa.Integer(), nullable=True, comment='Total session time in seconds'))
    op.add_column('trainings', sa.Column('visibility_mode', sa.Enum('solo', 'private', name='visibility_mode'), nullable=True))
    op.add_column('trainings', sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='difficulty_level'), nullable=True))
    op.add_column('trainings', sa.Column('eye_calibration', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Raw calibration JSON from frontend'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainings', 'eye_calibration')
    op.drop_column('trainings', 'difficulty')
    op.drop_column('trainings', 'visibility_mode')
    op.drop_column('trainings', 'duration_seconds')
    # ### end Alembic commands ###
