"""empty message

Revision ID: cff98534dec4
Revises: 0907655e3aaa
Create Date: 2025-06-22 21:17:54.767003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cff98534dec4'
down_revision: Union[str, Sequence[str], None] = '0907655e3aaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainings', sa.Column('slide_events', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='List of slide change events as [{timestamp, page}]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainings', 'slide_events')
    # ### end Alembic commands ###
