"""empty message

Revision ID: d4a736b1c6f1
Revises: 8346b5ac5174
Create Date: 2025-06-21 22:08:31.716078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd4a736b1c6f1'
down_revision: Union[str, Sequence[str], None] = '8346b5ac5174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trainings', 'eye_tracking_scores',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Heatmap der Blickpunkte',
               existing_comment='Heatmap/Score aus Eye Tracking',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trainings', 'eye_tracking_scores',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Heatmap/Score aus Eye Tracking',
               existing_comment='Heatmap der Blickpunkte',
               existing_nullable=True)
    # ### end Alembic commands ###
