"""Split findings into separate table

Revision ID: e2c31ae2a80c
Revises: 176a4800ea4e
Create Date: 2025-06-19 16:04:45.101561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2c31ae2a80c'
down_revision: Union[str, Sequence[str], None] = '176a4800ea4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presentation_findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('presentation_id', sa.UUID(), nullable=False),
    sa.Column('findings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('cockpit_score', sa.Float(), nullable=True),
    sa.Column('flight_path_score', sa.Float(), nullable=True),
    sa.Column('altitude_score', sa.Float(), nullable=True),
    sa.Column('preflight_check_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['presentation_id'], ['presentations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('presentations', 'findings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('presentations', sa.Column('findings', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_table('presentation_findings')
    # ### end Alembic commands ###
