"""empty message

Revision ID: e4666620d2e1
Revises: 255e1c6ac1a9
Create Date: 2025-06-20 12:15:26.952180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4666620d2e1'
down_revision: Union[str, Sequence[str], None] = '255e1c6ac1a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainings', sa.Column('video_url', sa.Text(), nullable=True, comment='Permanent MinIO URL for the recording'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainings', 'video_url')
    # ### end Alembic commands ###
